[workspace]
members = [
	"crates/meilisearch-operator",
	"crates/meili-crds",
	"crates/meili-shared",
	"crates/meili-index-controller",
	"crates/meili-key-controller",
	"crates/meili-server-controller",
	"crates/meili-metrics",
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Meili Operator Authors"]
license = "Apache-2.0"
