[package]
name = "meili-metrics"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
actix-web = "4"
prometheus = { version = "0.13", default-features = false, features = ["process"] }
tokio = { version = "1", features = ["rt", "macros", "time"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
meilisearch-sdk = "0.30"
kube = { version = "2.0.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
meili-crds = { path = "../meili-crds" }
