[package]
name = "meilisearch-operator"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
rand = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "signal"] }
futures = "0.3"
time = { version = "0.3", features = ["parsing", "formatting"] }

kube = { version = "2.0.1", features = ["runtime", "derive"] }
schemars = "1"
serde_yaml = "0.9"
meili-index-controller = { path = "../meili-index-controller" }
meili-key-controller = { path = "../meili-key-controller" }
meili-server-controller = { path = "../meili-server-controller" }
meili-crds = { path = "../meili-crds" }
meili-metrics = { path = "../meili-metrics" }

[dev-dependencies]
tokio = { version = "1.48", features = ["macros", "rt-multi-thread", "time"] }
serde_json = "1"
axum = { version = "0.8", default-features = false, features = ["tokio", "http1"] }
