[package]
name = "meili-server-controller"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
tracing = "0.1"
rand = "0.9"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["time"] }
kube = { version = "2.0.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
meili-crds = { path = "../meili-crds" }
meili-shared = { path = "../meili-shared" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
axum = { version = "0.8", default-features = false, features = ["tokio", "http1"] }
